# Generated by Django 2.1.15 on 2021-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_auto_20210311_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='bytesave_cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ustomer_byteSave', models.IntegerField()),
                ('bytesave_amount_used', models.IntegerField(default=1)),
                ('bytesave_duration', models.IntegerField(blank=True, null=True)),
                ('bytesave_time_type', models.IntegerField(default=1)),
                ('bytesave_expiration_date', models.CharField(blank=True, max_length=250, null=True)),
                ('is_del', models.IntegerField(default=0)),
                ('time_create_at', models.IntegerField(default=1615999212)),
                ('time_update_at', models.IntegerField(default=1615999212)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer_bytesave',
            name='bytesave_amount_used',
        ),
        migrations.RemoveField(
            model_name='customer_bytesave',
            name='bytesave_duration',
        ),
        migrations.RemoveField(
            model_name='customer_bytesave',
            name='bytesave_expiration_date',
        ),
        migrations.RemoveField(
            model_name='customer_bytesave',
            name='bytesave_time_type',
        ),
        migrations.AlterField(
            model_name='agents',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='agents',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='backup_bytesave',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='backup_bytesave',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='connect_bytesave',
            name='time_check_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='connect_bytesave',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='connect_bytesave',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='customer_bytesave',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='customer_bytesave',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='customer_represent',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='customer_represent',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='customers',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='customers',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='loggin',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='loggin',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='metric_services',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='metric_services',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='service',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='service',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='setting_bytesave',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='setting_bytesave',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='versions',
            name='time_create_at',
            field=models.IntegerField(default=1615999212),
        ),
        migrations.AlterField(
            model_name='versions',
            name='time_update_at',
            field=models.IntegerField(default=1615999212),
        ),
    ]
