# Generated by Django 2.1.15 on 2021-03-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0032_auto_20210318_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_content', models.CharField(blank=True, max_length=500)),
                ('function', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(blank=True, max_length=250)),
                ('time_log', models.IntegerField(default=1616147535)),
                ('time_create_at', models.IntegerField(default=1616147535)),
                ('time_update_at', models.IntegerField(default=1616147535)),
            ],
        ),
        migrations.AlterField(
            model_name='agents',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='agents',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='backup_bytesave',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='backup_bytesave',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='bytesave_cycle',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='bytesave_cycle',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='connect_bytesave',
            name='time_check_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='connect_bytesave',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='connect_bytesave',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='customer_bytesave',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='customer_bytesave',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='customer_represent',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='customer_represent',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='customers',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='customers',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='loggin',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='loggin',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='metric_services',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='metric_services',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='service',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='service',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='setting_bytesave',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='setting_bytesave',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='versions',
            name='time_create_at',
            field=models.IntegerField(default=1616147535),
        ),
        migrations.AlterField(
            model_name='versions',
            name='time_update_at',
            field=models.IntegerField(default=1616147535),
        ),
    ]
